---
 - name: Install PHP
   sudo: yes
   apt: name={{ item }} state=latest update_cache=yes
   with_items:
     - php5-fpm
#     - php5-mcrypt
#     - php5-mysqlnd
#     - php5-cli
#     - php5-intl
#     - php5-curl
#     - php5-json
#     - php5-mongo
 - name: ensure php-fpm is running
   service: name=php5-fpm state=started
